// Constants used in models
const consts = {
  // Users: role
  USER_ROLE_ADMIN: 1,
  USER_ROLE_AGENT: 6,
  USER_ROLE_KEEPER: 7,
  USER_ROLE_ASSIGNER: 8,
  USER_ROLE_TESTER: 9,
  USER_ROLE_NORMAL: 20,
  USER_ROLE_DISABLED: 30,
  USER_ROLE_DELETED: 31,

  // Users: history type
  USER_HISTORY_TYPE_ADD_FUNDS: 1,
  USER_HISTORY_TYPE_PAY: 2,
  USER_HISTORY_TYPE_REFUND: 3,

  // Users: System Generated extra events
  USER_EXTRA_TYPE_CHANGE_LOGIN_PASSWORD: 21,
  USER_EXTRA_TYPE_SET_PAYMENT_PASSWORD: 22,
  USER_EXTRA_TYPE_CHANGE_PAYMENT_PASSWORD: 23,
  USER_EXTRA_TYPE_SET_DEFAULT_ADDRESS: 24,
  USER_EXTRA_TYPE_ADD_NEW_ADDRESS: 25,
  USER_EXTRA_TYPE_CHANGE_SET_DEFAULT_ADDRESS: 26,
  USER_EXTRA_TYPE_CHANGE_ADDRESS: 27,
  USER_EXTRA_TYPE_REMOVE_ADDRESS: 28,
  USER_EXTRA_TYPE_SET_AVATAR: 29,
  USER_EXTRA_TYPE_ACCOUNT_SETTING: 30,

  // Orders: status
  ORDER_STATUS_UNCLAIMED: 1,
  ORDER_STATUS_CLAIMED: 2,
  ORDER_STATUS_REJECTED: 3,
  ORDER_STATUS_APPROVED: 4,
  ORDER_STATUS_CLOSED: 5,
  ORDER_STATUS_PAID: 6,
  ORDER_STATUS_PROCESSED: 7,
  ORDER_STATUS_SAMPLE_RECEIVED: 8,
  ORDER_STATUS_ASSIGNED: 9,
  ORDER_STATUS_TESTED: 10,
  ORDER_STATUS_REPORT_SHIPPED: 11,
  ORDER_STATUS_COMPLETED: 12,
  ORDER_STATUS_REFUNDED: 13,

  // Orders: sample disposal type
  ORDER_SAMPLE_DISPOSAL_TYPE_TAKE_BACK: 1,
  ORDER_SAMPLE_DISPOSAL_TYPE_THROW_AWAY: 2,

  // Orders: report fetching type
  ORDER_REPORT_FETCHING_TYPE_PICK_UP: 1,
  ORDER_REPORT_FETCHING_TYPE_MAIL_BACK: 2,

  // Recharges/Payments: method
  PAYMENT_METHOD_ALIPAY: 1,
  PAYMENT_METHOD_WECHAT: 2,
};

export default Object.freeze(consts);
